#!/usr/bin/env python3
"""Generate Shruthi factory preset data for SWARA XT from upstream factory_data.txt."""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
FACTORY_FILE = REPO_ROOT / "third_party/shruthi-1/shruthi/data/factory_data/factory_data.txt"
OUTPUT_HEADER = REPO_ROOT / "Source/Plugin/ShruthiFactoryPresetData.h"

# Authoritative requested set (order preserved).
PRESET_CATALOG = [
    ("Florian Fourmy", "Flo bass"),
    ("Florian Fourmy", "Follow!"),
    ("Florian Fourmy", "ElectroB"),
    ("stuartm", "woblbass"),
    ("stuartm", "digobass"),
    ("stuartm", "pythagor"),
    ("stuartm", "noleleva"),
    ("stuartm", "ahhparis"),
    ("stuartm", "repliknt"),
    ("stuartm", "pwmstrng"),
    ("stuartm", "dahkand"),
    ("stuartm", "deetoon"),
    ("stuartm", "cowgirl"),
    ("stuartm", "voxelito"),
    ("stuartm", "woodtock"),
    ("Trackdriver", "bitbass"),
    ("Trackdriver", "shorty"),
    ("Trackdriver", "VICdbass"),
    ("Trackdriver", "sawwy"),
    ("Trackdriver", "reason"),
    ("Trackdriver", "puddle"),
    ("Trackdriver", "blopbass"),
    ("Trackdriver", "borg"),
    ("Trackdriver", "fatbass"),
    ("Trackdriver", "wowwy"),
    ("Trackdriver", "pulsar"),
    ("Trackdriver", "stringe"),
    ("Trackdriver", "bigStrng"),
    ("Trackdriver", "simplBra"),
    ("Trackdriver", "pwmBrass"),
    ("Trackdriver", "arpSynth"),
    ("Trackdriver", "wasp"),
    ("Trackdriver", "rendezVo"),
    ("Trackdriver", "fullbell"),
    ("Trackdriver", "loFiFlut"),
    ("Trackdriver", "NESsie"),
    ("Trackdriver", "noisBell"),
    ("Trackdriver", "woice"),
    ("Trackdriver", "wavesurf"),
    ("Trackdriver", "lazrBird"),
]

# Map requested display names to upstream factory_data.txt patch names.
UPSTREAM_NAME = {
    "Flo bass": "flo bass",
    "Follow!": "follow !",
    "ElectroB": "electroB",
    "VICdbass": "VICdBass",
}


def normalize_lookup(name: str) -> str:
    return re.sub(r"[^a-z0-9]", "", name.lower())


def load_factory_patches() -> dict[str, tuple[str, str]]:
    patches: dict[str, tuple[str, str]] = {}
    for line in FACTORY_FILE.read_text(encoding="utf-8", errors="replace").splitlines():
        match = re.match(r"^patch\s+(.+?)\s+([0-9a-fA-F]+)\s*$", line.strip())
        if not match:
            continue
        upstream_name = match.group(1).strip()
        hex_data = match.group(2).strip().lower()
        if len(hex_data) % 2 != 0:
            raise ValueError(f"Odd hex length for patch {upstream_name!r}")
        patches[normalize_lookup(upstream_name)] = (upstream_name, hex_data)
    return patches


def main() -> None:
    upstream = load_factory_patches()
    entries: list[tuple[str, str, str, bytes]] = []

    for author, display_name in PRESET_CATALOG:
        source_name = UPSTREAM_NAME.get(display_name, display_name)
        key = normalize_lookup(source_name)
        if key not in upstream:
            raise SystemExit(f"Missing upstream patch for {display_name!r} (source {source_name!r})")
        upstream_name, hex_data = upstream[key]
        raw = bytes.fromhex(hex_data)
        if len(raw) != 92:
            raise SystemExit(f"Patch {display_name!r} expected 92 bytes, got {len(raw)}")
        entries.append((display_name, author, upstream_name, raw))

    lines = [
        "// Copyright 2026 MontroneDSP.",
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// Generated by Tools/generate_shruthi_factory_presets.py — do not edit by hand.",
        "",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace swaraxt {",
        "",
        "inline constexpr std::size_t kShruthiFactoryPresetCount = 40;",
        "inline constexpr std::size_t kShruthiFactoryPresetBytes = 92;",
        "",
        "struct ShruthiFactoryPresetRecord {",
        "    const char* displayName;",
        "    const char* author;",
        "    const char* upstreamName;",
        "    std::array<std::uint8_t, kShruthiFactoryPresetBytes> bytes;",
        "};",
        "",
        "inline constexpr ShruthiFactoryPresetRecord kShruthiFactoryPresets[kShruthiFactoryPresetCount] = {",
    ]

    for display_name, author, upstream_name, raw in entries:
        byte_list = ", ".join(f"0x{b:02x}" for b in raw)
        lines.append("    {")
        lines.append(f'        "{display_name}",')
        lines.append(f'        "{author}",')
        lines.append(f'        "{upstream_name}",')
        lines.append(f"        {{ {byte_list} }},")
        lines.append("    },")

    lines.extend(
        [
            "};",
            "",
            "}  // namespace swaraxt",
            "",
        ]
    )

    OUTPUT_HEADER.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT_HEADER} ({len(entries)} presets)")


if __name__ == "__main__":
    main()
