# SPDX-FileCopyrightText: 2026 MontroneDSP
# SPDX-License-Identifier: GPL-3.0-or-later

name: REUSE compliance

on:
  push:
  pull_request:

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: fsfe/reuse-action@v6
